import os
import json
import datetime
from beem import Hive
from beem.comment import Comment

POSTING_KEY = os.getenv('HIVE_POSTING_KEY')
HIVE_USER = os.getenv('HIVE_USER')

def make_post():
    if not POSTING_KEY or not HIVE_USER:
        print("Missing credentials")
        return
    hive = Hive(keys=[POSTING_KEY])
    title = "AI Trend: Automated Hive Blogging"
    body = "This post was automatically generated by Claude AI and published to Hive blockchain via GitHub Actions. No manual work, fully automated."
    permlink = f"{datetime.datetime.utcnow():%Y-%m-%d-%H-%M-%S}-ai-auto-post"
    comment = Comment(title=title, body=body, author=HIVE_USER, permlink=permlink, parent_author="", parent_permlink="hive", json_metadata=json.dumps({"tags":["ai","kr","automation"]}))
    comment.post()
    print(f"Posted successfully! URL: https://hive.io/@{HIVE_USER}/{permlink}")

if __name__ == '__main__':
    make_post()
