name: Auto Hive Post
on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run script
        env:
          HIVE_USER: ${{ secrets.HIVE_USER }}
        run: python post_to_hive.py
